version: "3"
services:
    elasticsearch:
      image: elasticsearch:7.17.10
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - discovery.type=single-node
    kibana:
      image: kibana:7.17.10
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
    apm-server:
      image: elastic/apm-server:7.17.10
      ports:
        - "8200:8200"
      volumes:
        - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
        - kibana
    redis:
      image: redis:7-alpine
    postgresql:
      image: postgres:15-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        - ./db/listen_all.sh:/docker-entrypoint-initdb.d/listen_all.sh
    ads-order:
      build:
        context: .
        dockerfile: Dockerfile
      image: ads-order:latest
      ports:
        - "8004:8000"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        - ELASTIC_APM_SERVER_URL=http://apm-server:8200
        - REDIS_URL=redis://redis:6379/0
        - POSTGRESQL_URL=postgresql://postgres:postgres@postgresql:5432/postgres?sslmode=disable
        - PRODUCT_SERVICE_URL=http://host.docker.internal:8001
        - EXCHANGE_SERVICE_URL=http://host.docker.internal:8002
        - PAYMENT_SERVICE_URL=http://host.docker.internal:8003
